file_path: 'data/pretrain_1M.csv'

# Training parameters
epochs: 5
batch_size: 64
lr_rate: 0.00005
scheduler_type: 'linear'
weight_decay: 0.0
warmup_ratio: 0.05
save_strategy: 'epoch'
overwrite_output_dir: True
save_total_limit: 2
fp16: True
logging_strategy: 'epoch'
evaluation_strategy: 'epoch'
report_to: 'tensorboard'
dataloader_num_workers: 4
sharded_ddp: False
save_path: 'ckpt/poc_model.pt'
load_checkpoint: False

# Model architecture
max_position_embeddings: 514
blocksize: 175
num_attention_heads: 12
num_hidden_layers: 6
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
mlm_probability: 0.15
